#include <flex.h>
bool flex::decode_GB_ATTENTION_CHILD_gb_attention_child_next_shift() {
sc_biguint<1> local_var_1 = 1;
bool local_var_2 = (flex_gb_attention_child_valid_flag == local_var_1);
sc_biguint<5> local_var_4 = 5;
bool local_var_5 = (flex_gb_attention_child_state == local_var_4);
bool local_var_6 = (local_var_2 & local_var_5);
auto& univ_var_537 = local_var_6;
return univ_var_537;
}
void flex::update_GB_ATTENTION_CHILD_gb_attention_child_next_shift() {
sc_biguint<5> local_var_0 = 6;
auto local_var_0_nxt_holder = local_var_0;
sc_biguint<2> local_var_2 = 0;
bool local_var_3 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_2);
sc_biguint<2> local_var_5 = 1;
bool local_var_6 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_5);
sc_biguint<2> local_var_8 = 2;
bool local_var_9 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_8);
auto local_var_12 = (local_var_9) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_8 : GB_ATTENTION_CHILD_gb_attention_accum_vector_12;
auto local_var_13 = (local_var_6) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_4 : local_var_12;
auto local_var_14 = (local_var_3) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_0 : local_var_13;
sc_biguint<32> local_var_15 = 0;
bool local_var_16 = (local_var_14 == local_var_15);
sc_biguint<32> local_var_17 = 4227858432;
sc_biguint<29> local_var_18 = 0;
univ_var_538 = (sc_biguint<29>(local_var_18), sc_biguint<3>(flex_gb_attention_adpbias_1));
sc_biguint<29> local_var_21 = 0;
univ_var_539 = (sc_biguint<29>(local_var_21), sc_biguint<3>(flex_gb_attention_adpbias_2));
sc_biguint<32> local_var_24 = (univ_var_538 + univ_var_539);
sc_biguint<32> local_var_25 = 8;
bool local_var_26 = (local_var_24 > local_var_25);
sc_biguint<32> local_var_27 = 8;
sc_biguint<32> local_var_28 = (local_var_24 - local_var_27);
sc_biguint<32> local_var_29 = 8;
sc_biguint<32> local_var_30 = (local_var_29 - local_var_24);
auto local_var_31 = (local_var_26) ? local_var_28 : local_var_30;
auto local_var_32 = GBAttentionLSH(local_var_14, local_var_31);
auto local_var_33 = GBAttentionRSH(local_var_14, local_var_31);
auto local_var_34 = (local_var_26) ? local_var_32 : local_var_33;
auto local_var_35 = (local_var_16) ? local_var_17 : local_var_34;
auto local_var_35_nxt_holder = local_var_35;
sc_biguint<2> local_var_36 = 0;
bool local_var_37 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_36);
sc_biguint<2> local_var_39 = 1;
bool local_var_40 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_39);
sc_biguint<2> local_var_42 = 2;
bool local_var_43 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_42);
auto local_var_46 = (local_var_43) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_9 : GB_ATTENTION_CHILD_gb_attention_accum_vector_13;
auto local_var_47 = (local_var_40) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_5 : local_var_46;
auto local_var_48 = (local_var_37) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_1 : local_var_47;
sc_biguint<32> local_var_49 = 0;
bool local_var_50 = (local_var_48 == local_var_49);
sc_biguint<32> local_var_51 = 4227858432;
auto local_var_52 = GBAttentionLSH(local_var_48, local_var_31);
auto local_var_53 = GBAttentionRSH(local_var_48, local_var_31);
auto local_var_54 = (local_var_26) ? local_var_52 : local_var_53;
auto local_var_55 = (local_var_50) ? local_var_51 : local_var_54;
auto local_var_55_nxt_holder = local_var_55;
sc_biguint<2> local_var_56 = 0;
bool local_var_57 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_56);
sc_biguint<2> local_var_59 = 1;
bool local_var_60 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_59);
sc_biguint<2> local_var_62 = 2;
bool local_var_63 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_62);
auto local_var_66 = (local_var_63) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_10 : GB_ATTENTION_CHILD_gb_attention_accum_vector_14;
auto local_var_67 = (local_var_60) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_6 : local_var_66;
auto local_var_68 = (local_var_57) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_2 : local_var_67;
sc_biguint<32> local_var_69 = 0;
bool local_var_70 = (local_var_68 == local_var_69);
sc_biguint<32> local_var_71 = 4227858432;
auto local_var_72 = GBAttentionLSH(local_var_68, local_var_31);
auto local_var_73 = GBAttentionRSH(local_var_68, local_var_31);
auto local_var_74 = (local_var_26) ? local_var_72 : local_var_73;
auto local_var_75 = (local_var_70) ? local_var_71 : local_var_74;
auto local_var_75_nxt_holder = local_var_75;
sc_biguint<2> local_var_76 = 0;
bool local_var_77 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_76);
sc_biguint<2> local_var_79 = 1;
bool local_var_80 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_79);
sc_biguint<2> local_var_82 = 2;
bool local_var_83 = (GB_ATTENTION_CHILD_gb_attention_softmax_cntr == local_var_82);
auto local_var_86 = (local_var_83) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_11 : GB_ATTENTION_CHILD_gb_attention_accum_vector_15;
auto local_var_87 = (local_var_80) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_7 : local_var_86;
auto local_var_88 = (local_var_77) ? GB_ATTENTION_CHILD_gb_attention_accum_vector_3 : local_var_87;
sc_biguint<32> local_var_89 = 0;
bool local_var_90 = (local_var_88 == local_var_89);
sc_biguint<32> local_var_91 = 4227858432;
auto local_var_92 = GBAttentionLSH(local_var_88, local_var_31);
auto local_var_93 = GBAttentionRSH(local_var_88, local_var_31);
auto local_var_94 = (local_var_26) ? local_var_92 : local_var_93;
auto local_var_95 = (local_var_90) ? local_var_91 : local_var_94;
auto local_var_95_nxt_holder = local_var_95;
flex_gb_attention_child_state = local_var_0_nxt_holder;
GB_ATTENTION_CHILD_gb_attention_vector_0 = local_var_35_nxt_holder;
GB_ATTENTION_CHILD_gb_attention_vector_1 = local_var_55_nxt_holder;
GB_ATTENTION_CHILD_gb_attention_vector_2 = local_var_75_nxt_holder;
GB_ATTENTION_CHILD_gb_attention_vector_3 = local_var_95_nxt_holder;
}
