g++ -I./ -c -o init_AES_BLOCK.o init_AES_BLOCK.cc
g++ -I./ -c -o decode_AES_WRITE_ADDRESS.o decode_AES_WRITE_ADDRESS.cc
g++ -I./ -c -o decode_AES_START_ENCRYPT.o decode_AES_START_ENCRYPT.cc
g++ -I./ -c -o decode_AES_READ_LENGTH.o decode_AES_READ_LENGTH.cc
g++ -I./ -c -o decode_AES_READ_ADDRESS.o decode_AES_READ_ADDRESS.cc
g++ -I./ -c -o decode_AES_READ_KEY.o decode_AES_READ_KEY.cc
g++ -I./ -c -o decode_AES_READ_COUNTER.o decode_AES_READ_COUNTER.cc
g++ -I./ -c -o decode_AES_GET_STATUS.o decode_AES_GET_STATUS.cc
g++ -I./ -c -o decode_AES_WRITE_LENGTH.o decode_AES_WRITE_LENGTH.cc
g++ -I./ -c -o decode_AES_WRITE_KEY.o decode_AES_WRITE_KEY.cc
g++ -I./ -c -o decode_AES_WRITE_COUNTER.o decode_AES_WRITE_COUNTER.cc
g++ -I./ -c -o decode_AES_BLOCK_LOAD.o decode_AES_BLOCK_LOAD.cc
g++ -I./ -c -o decode_AES_BLOCK_OPERATE.o decode_AES_BLOCK_OPERATE.cc
g++ -I./ -c -o decode_AES_BLOCK_STORE.o decode_AES_BLOCK_STORE.cc
g++ -I./ -c -o AES_WRITE_ADDRESS.o AES_WRITE_ADDRESS.cc
g++ -I./ -c -o AES_START_ENCRYPT.o AES_START_ENCRYPT.cc
g++ -I./ -c -o AES_READ_LENGTH.o AES_READ_LENGTH.cc
g++ -I./ -c -o AES_READ_ADDRESS.o AES_READ_ADDRESS.cc
g++ -I./ -c -o AES_READ_KEY.o AES_READ_KEY.cc
g++ -I./ -c -o AES_READ_COUNTER.o AES_READ_COUNTER.cc
g++ -I./ -c -o AES_GET_STATUS.o AES_GET_STATUS.cc
g++ -I./ -c -o AES_WRITE_LENGTH.o AES_WRITE_LENGTH.cc
g++ -I./ -c -o AES_WRITE_KEY.o AES_WRITE_KEY.cc
g++ -I./ -c -o AES_WRITE_COUNTER.o AES_WRITE_COUNTER.cc
g++ -I./ -c -o AES_BLOCK_LOAD.o AES_BLOCK_LOAD.cc
g++ -I./ -c -o AES_BLOCK_OPERATE.o AES_BLOCK_OPERATE.cc
g++ -I./ -c -o AES_BLOCK_STORE.o AES_BLOCK_STORE.cc
g++ -I./ -c -o compute.o compute.cc 
g++ -I./ -c -o help.o ../../uninterpreted_func/uninterpreted_func.cc 
