#include <flex.h>
bool flex::decode_GB_LAYER_REDUCE_gb_layer_reduce_timestep_level_op() {
sc_biguint<1> local_var_1 = 1;
bool local_var_2 = (flex_gb_layer_reduce_child_valid_flag == local_var_1);
sc_biguint<3> local_var_4 = 2;
bool local_var_5 = (flex_gb_layer_reduce_child_state == local_var_4);
bool local_var_6 = (local_var_2 & local_var_5);
auto& univ_var_745 = local_var_6;
return univ_var_745;
}
void flex::update_GB_LAYER_REDUCE_gb_layer_reduce_timestep_level_op() {
sc_biguint<3> local_var_0 = 3;
auto local_var_0_nxt_holder = local_var_0;
sc_biguint<16> local_var_2 = 2;
sc_biguint<16> local_var_3 = (GB_LAYER_REDUCE_gb_layer_reduce_timestep_cntr + local_var_2);
auto local_var_3_nxt_holder = local_var_3;
sc_biguint<4> local_var_4 = 0;
univ_var_746 = (sc_biguint<4>(local_var_4), sc_biguint<16>(GB_LAYER_REDUCE_gb_layer_reduce_timestep_cntr));
sc_biguint<20> local_var_6 = 16;
sc_biguint<20> local_var_7 = (univ_var_746 / local_var_6);
sc_biguint<12> local_var_8 = 0;
univ_var_747 = (sc_biguint<12>(local_var_8), sc_biguint<8>(flex_gb_layer_reduce_num_vector_1));
sc_biguint<20> local_var_11 = 16;
sc_biguint<20> local_var_12 = (univ_var_747 * local_var_11);
sc_biguint<20> local_var_13 = 16;
sc_biguint<20> local_var_14 = (local_var_12 * local_var_13);
sc_biguint<20> local_var_15 = (local_var_7 * local_var_14);
sc_biguint<20> local_var_16 = 16;
sc_biguint<20> local_var_17 = (univ_var_746 % local_var_16);
sc_biguint<20> local_var_18 = 16;
sc_biguint<20> local_var_19 = (local_var_17 * local_var_18);
sc_biguint<20> local_var_20 = (local_var_15 + local_var_19);
sc_biguint<3> local_var_22 = 0;
bool local_var_23 = (flex_gb_layer_reduce_memory_index_1 == local_var_22);
sc_biguint<4> local_var_25 = 0;
univ_var_748 = (sc_biguint<16>(flex_gb_core_mem_mngr_large_base_large_0), sc_biguint<4>(local_var_25));
sc_biguint<3> local_var_27 = 1;
bool local_var_28 = (flex_gb_layer_reduce_memory_index_1 == local_var_27);
sc_biguint<4> local_var_30 = 0;
univ_var_749 = (sc_biguint<16>(flex_gb_core_mem_mngr_large_base_large_1), sc_biguint<4>(local_var_30));
sc_biguint<3> local_var_32 = 2;
bool local_var_33 = (flex_gb_layer_reduce_memory_index_1 == local_var_32);
sc_biguint<4> local_var_35 = 0;
univ_var_750 = (sc_biguint<16>(flex_gb_core_mem_mngr_large_base_large_2), sc_biguint<4>(local_var_35));
sc_biguint<4> local_var_38 = 0;
univ_var_751 = (sc_biguint<16>(flex_gb_core_mem_mngr_large_base_large_3), sc_biguint<4>(local_var_38));
auto local_var_40 = (local_var_33) ? univ_var_750 : univ_var_751;
auto local_var_41 = (local_var_28) ? univ_var_749 : local_var_40;
auto local_var_42 = (local_var_23) ? univ_var_748 : local_var_41;
sc_biguint<20> local_var_43 = (local_var_20 + local_var_42);
auto local_var_43_nxt_holder = local_var_43;
sc_biguint<20> local_var_44 = 1;
sc_biguint<20> local_var_45 = (univ_var_746 + local_var_44);
sc_biguint<20> local_var_46 = 16;
sc_biguint<20> local_var_47 = (local_var_45 / local_var_46);
sc_biguint<20> local_var_48 = (local_var_47 * local_var_14);
sc_biguint<20> local_var_49 = 16;
sc_biguint<20> local_var_50 = (local_var_45 % local_var_49);
sc_biguint<20> local_var_51 = 16;
sc_biguint<20> local_var_52 = (local_var_50 * local_var_51);
sc_biguint<20> local_var_53 = (local_var_48 + local_var_52);
sc_biguint<20> local_var_54 = (local_var_53 + local_var_42);
auto local_var_54_nxt_holder = local_var_54;
sc_biguint<20> local_var_55 = 2;
sc_biguint<20> local_var_56 = (univ_var_746 / local_var_55);
sc_biguint<20> local_var_57 = 16;
sc_biguint<20> local_var_58 = (local_var_56 / local_var_57);
sc_biguint<20> local_var_59 = (local_var_58 * local_var_14);
sc_biguint<20> local_var_60 = 16;
sc_biguint<20> local_var_61 = (local_var_56 % local_var_60);
sc_biguint<20> local_var_62 = 16;
sc_biguint<20> local_var_63 = (local_var_61 * local_var_62);
sc_biguint<20> local_var_64 = (local_var_59 + local_var_63);
sc_biguint<20> local_var_65 = (local_var_64 + local_var_42);
auto local_var_65_nxt_holder = local_var_65;
sc_biguint<8> local_var_66 = 0;
auto local_var_66_nxt_holder = local_var_66;
flex_gb_layer_reduce_child_state = local_var_0_nxt_holder;
GB_LAYER_REDUCE_gb_layer_reduce_timestep_cntr = local_var_3_nxt_holder;
GB_LAYER_REDUCE_gb_layer_reduce_timestep_level_base_addr_0 = local_var_43_nxt_holder;
GB_LAYER_REDUCE_gb_layer_reduce_timestep_level_base_addr_1 = local_var_54_nxt_holder;
GB_LAYER_REDUCE_gb_layer_reduce_timestep_level_base_addr_result = local_var_65_nxt_holder;
GB_LAYER_REDUCE_gb_layer_reduce_vector_cntr = local_var_66_nxt_holder;
}
