#include <flex.h>
bool flex::decode_PE1_CORE_CHILD_PE1_core_out() {
sc_biguint<1> local_var_1 = 1;
bool local_var_2 = (flex_pe1_rnn_layer_sizing_is_valid == local_var_1);
sc_biguint<1> local_var_4 = 1;
bool local_var_5 = (PE1_CORE_CHILD_pe1_core_is_start == local_var_4);
bool local_var_6 = (local_var_2 & local_var_5);
sc_biguint<3> local_var_8 = 4;
bool local_var_9 = (flex_pe1_core_state == local_var_8);
bool local_var_10 = (local_var_6 & local_var_9);
sc_biguint<1> local_var_12 = 0;
bool local_var_13 = (flex_pe1_act_reg_port_valid == local_var_12);
bool local_var_14 = (local_var_10 & local_var_13);
auto& univ_var_74 = local_var_14;
return univ_var_74;
}
void flex::update_PE1_CORE_CHILD_PE1_core_out() {
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_0_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_0;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_1_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_1;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_10_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_10;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_11_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_11;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_12_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_12;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_13_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_13;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_14_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_14;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_15_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_15;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_2_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_2;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_3_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_3;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_4_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_4;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_5_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_5;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_6_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_6;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_7_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_7;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_8_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_8;
auto PE1_CORE_CHILD_PE1_core_act_vector_reg_9_nxt_holder = PE1_CORE_CHILD_PE1_core_act_vector_reg_9;
sc_biguint<1> local_var_16 = 1;
auto local_var_16_nxt_holder = local_var_16;
sc_biguint<3> local_var_17 = 0;
univ_var_75 = (sc_biguint<3>(local_var_17), sc_biguint<1>(PE1_CORE_CHILD_pe1_core_manager_cntr));
sc_biguint<4> local_var_21 = 1;
sc_biguint<4> local_var_22 = (flex_pe1_rnn_layer_sizing_num_manager - local_var_21);
bool local_var_23 = (univ_var_75 == local_var_22);
sc_biguint<8> local_var_26 = 1;
sc_biguint<8> local_var_27 = (flex_pe1_rnn_layer_sizing_num_output - local_var_26);
bool local_var_28 = (PE1_CORE_CHILD_pe1_core_output_counter == local_var_27);
bool local_var_29 = (local_var_23 & local_var_28);
sc_biguint<3> local_var_30 = 0;
sc_biguint<3> local_var_31 = 1;
auto local_var_32 = (local_var_29) ? local_var_30 : local_var_31;
auto local_var_32_nxt_holder = local_var_32;
sc_biguint<1> local_var_33 = 0;
sc_biguint<1> local_var_34 = 1;
sc_biguint<1> local_var_35 = (PE1_CORE_CHILD_pe1_core_manager_cntr + local_var_34);
auto local_var_36 = (local_var_23) ? local_var_33 : local_var_35;
auto local_var_36_nxt_holder = local_var_36;
bool local_var_37 = (local_var_23 & local_var_28);
sc_biguint<8> local_var_38 = 0;
bool local_var_39 = !local_var_28;
bool local_var_40 = (local_var_23 & local_var_39);
sc_biguint<8> local_var_41 = 1;
sc_biguint<8> local_var_42 = (PE1_CORE_CHILD_pe1_core_output_counter + local_var_41);
auto local_var_43 = (local_var_40) ? local_var_42 : PE1_CORE_CHILD_pe1_core_output_counter;
auto local_var_44 = (local_var_37) ? local_var_38 : local_var_43;
auto local_var_44_nxt_holder = local_var_44;
sc_biguint<3> local_var_45 = 0;
sc_biguint<3> local_var_46 = 1;
auto local_var_47 = (local_var_29) ? local_var_45 : local_var_46;
auto local_var_47_nxt_holder = local_var_47;
bool local_var_48 = (local_var_23 & local_var_28);
sc_biguint<1> local_var_49 = 0;
auto local_var_51 = (local_var_48) ? local_var_49 : flex_pe1_rnn_layer_sizing_is_zero_first;
auto local_var_51_nxt_holder = local_var_51;
flex_PE1_core_act_vector_0 = PE1_CORE_CHILD_PE1_core_act_vector_reg_0_nxt_holder;
flex_PE1_core_act_vector_1 = PE1_CORE_CHILD_PE1_core_act_vector_reg_1_nxt_holder;
flex_PE1_core_act_vector_10 = PE1_CORE_CHILD_PE1_core_act_vector_reg_10_nxt_holder;
flex_PE1_core_act_vector_11 = PE1_CORE_CHILD_PE1_core_act_vector_reg_11_nxt_holder;
flex_PE1_core_act_vector_12 = PE1_CORE_CHILD_PE1_core_act_vector_reg_12_nxt_holder;
flex_PE1_core_act_vector_13 = PE1_CORE_CHILD_PE1_core_act_vector_reg_13_nxt_holder;
flex_PE1_core_act_vector_14 = PE1_CORE_CHILD_PE1_core_act_vector_reg_14_nxt_holder;
flex_PE1_core_act_vector_15 = PE1_CORE_CHILD_PE1_core_act_vector_reg_15_nxt_holder;
flex_PE1_core_act_vector_2 = PE1_CORE_CHILD_PE1_core_act_vector_reg_2_nxt_holder;
flex_PE1_core_act_vector_3 = PE1_CORE_CHILD_PE1_core_act_vector_reg_3_nxt_holder;
flex_PE1_core_act_vector_4 = PE1_CORE_CHILD_PE1_core_act_vector_reg_4_nxt_holder;
flex_PE1_core_act_vector_5 = PE1_CORE_CHILD_PE1_core_act_vector_reg_5_nxt_holder;
flex_PE1_core_act_vector_6 = PE1_CORE_CHILD_PE1_core_act_vector_reg_6_nxt_holder;
flex_PE1_core_act_vector_7 = PE1_CORE_CHILD_PE1_core_act_vector_reg_7_nxt_holder;
flex_PE1_core_act_vector_8 = PE1_CORE_CHILD_PE1_core_act_vector_reg_8_nxt_holder;
flex_PE1_core_act_vector_9 = PE1_CORE_CHILD_PE1_core_act_vector_reg_9_nxt_holder;
flex_pe1_act_reg_port_valid = local_var_16_nxt_holder;
PE1_CORE_CHILD_pe1_core_is_start = local_var_32_nxt_holder;
PE1_CORE_CHILD_pe1_core_manager_cntr = local_var_36_nxt_holder;
PE1_CORE_CHILD_pe1_core_output_counter = local_var_44_nxt_holder;
flex_pe1_core_state = local_var_47_nxt_holder;
flex_pe1_rnn_layer_sizing_is_zero_first = local_var_51_nxt_holder;
}
